// src/colors/vue/components/inputs/base/InputNumber.vue
<script setup lang="ts">
const props = defineProps<{
  value: number
  title: string
  min?: number
  max?: number
  step?: number
  width?: number
}>()

const min = props.min ?? 0
const max = props.max ?? 100
const step = props.step ?? 1
const width = props.width ?? 64

const emit = defineEmits(['input'])

const onChange = (e: Event) => {
  const value = (e.target as HTMLInputElement).value
  let number = Number(value)
  emit('input', number)
}
</script>

<template>
  <input
    class="input-number"
    type="number"
    :min="min"
    :max="max"
    :step="step"
    :value="props.value"
    :title="props.title"
    @change="onChange"
    :style="{ width: `${width}px` }"
  />
</template>

<style scoped>
.input-number {
  text-align: right;
  font-size: 18px;
  appearance: textfield;
  -moz-appearance: textfield;
}
</style>

// src/colors/svelte/components/inputs/base/InputNumber.svelte
<script lang="ts">
  type Props = {
    value: number
    title: string
    min?: number
    max?: number
    step?: number
    width?: number
    onInput: (value: number) => void
  }

  const { value, title, min = 0, max = 100, step = 1, width = 64, onInput }: Props = $props()

  const onChange = (e: Event) => {
    const target = e.target as HTMLInputElement
    const value = Number(target.value)
    onInput(value)
  }
</script>

<input
  class="input-number"
  type="number"
  {min}
  {max}
  {step}
  {value}
  {title}
  onchange={onChange}
  style={`width: ${width}px`}
/>

<style scoped>
  .input-number {
    text-align: right;
    font-size: 18px;
    appearance: textfield;
    -moz-appearance: textfield;
  }
</style>
