// src/colors/svelte/components/FullScreen.svelte
<script lang="ts">
  import { bgColorHSL } from '@svelte/helpers/style'
  import { fullScreen, hsl, toggleFullScreen } from '@svelte/store'
</script>

<button
  style={bgColorHSL($hsl)}
  class={$fullScreen ? 'fullscreen show' : 'fullscreen hide'}
  onclick={toggleFullScreen}
  aria-label="Toggle Fullscreen"
></button>

<style scoped>
  .fullscreen {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    border: none;
    border-radius: 0;
    &.hide {
      display: none;
    }
    &.show {
      display: block;
    }
  }
</style>

// src/colors/react/components/FullScreen.tsx
import { bgColorHSL } from '@react/helpers/style'
import { toggleFullScreen } from '@react/actions'
import { useMemo } from 'react'
import styles from '@react/components/FullScreen.module.css'
import { fullScreen, hsl } from '@react/signals'

const FullScreen = () => {
  const className = useMemo(() => {
    const classes = [styles.fullscreen]
    if (fullScreen.value) {
      classes.push(styles.show)
    } else {
      classes.push(styles.hide)
    }
    return classes.join(' ')
  }, [fullScreen])

  return <button
    style={bgColorHSL(hsl.value)}
    className={className}
    onClick={toggleFullScreen}
    aria-label="Toggle Fullscreen"
  ></button>
}

export default FullScreen
