// src/colors/vue/components/Actions.vue
<script setup lang="ts">
import { colorSelected, hsl, palette, setPalette, unsetSelected } from '@vue/store'
import type { Color } from '@lib/types'

const add = (color: Color) => {
  if (!palette.value) return
  if (palette.value.find((c) => c.name === color.name)) {
    alert('Color name already exists')
    return
  }
  const paletteNew = [...palette.value, color]
  setPalette(paletteNew)
}

const remove = (color: Color) => {
  if (!palette.value) return
  const paletteNew = palette.value.filter((c) => c !== color)
  setPalette(paletteNew)
}

const onSave = async () => {
  const name = prompt('Color Name?')
  if (!name) return
  const colorNew = { name, hsl: hsl.value }
  add(colorNew)
}

const onRemove = async () => {
  if (!colorSelected.value) return
  const confirmed = confirm(`Are you sure you want to remove color "${colorSelected.value.name}"?`)
  if (!confirmed) return
  remove(colorSelected.value)
  unsetSelected()
}
</script>

<template>
<div class="actions">
  <button @click="onSave">Add</button>
  <button @click="onRemove" :disabled="!colorSelected">Remove</button>
</div>
</template>

<style scoped>
.actions {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}
</style>

// src/colors/svelte/components/Actions.svelte
<script lang="ts">
  import { palette, selected, hsl, setPalette, unsetSelected } from '@svelte/store'
  import type { Color } from '@lib/types'

  const add = async (color: Color) => {
    if ($palette.find((c) => c.name === color.name)) {
      alert('Color name already exists')
      return
    }
    const paletteNew = [...$palette, color]
    await setPalette(paletteNew)
  }

  const remove = async (color: Color) => {
    const paletteNew = $palette.filter((c) => c !== color)
    await setPalette(paletteNew)
  }

  const onSave = async () => {
    const name = prompt('Color Name?')
    if (!name) return
    const colorNew = { name, hsl: $hsl }
    add(colorNew)
  }

  const onRemove = async () => {
    const cs = $selected
    if (!cs) return
    const confirmed = confirm(`Are you sure you want to remove color "${cs.name}"?`)
    if (!confirmed) return
    remove(cs)
    unsetSelected()
  }
</script>

<div class="actions">
  <button onclick={onSave}>Add</button>
  <button onclick={onRemove} disabled={!$selected}>Remove</button>
</div>

<style scoped>
  .actions {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
  }
</style>
