// src/colors/svelte/components/inputs/colors/InputHSL.svelte
<script lang="ts">
  import InputNumber from '@svelte/components/inputs/base/InputNumber.svelte'
  import type { HSL } from 'color-convert/conversions'

  type Props = {
    value: HSL
    onInput: (value: HSL) => void
  }

  const { value, onInput }: Props = $props()

  const onHue = (newHue: number) => {
    const newHSL: HSL = [newHue, value[1], value[2]]
    onInput(newHSL)
  }

  const onSaturation = (newSaturation: number) => {
    const newHSL: HSL = [value[0], newSaturation, value[2]]
    onInput(newHSL)
  }

  const onLightness = (newLightness: number) => {
    const newHSL: HSL = [value[0], value[1], newLightness]
    onInput(newHSL)
  }
</script>

<InputNumber value={value[0]} title="Hue" max={360} onInput={onHue} />
<InputNumber value={value[1]} title="Saturation" onInput={onSaturation} />
<InputNumber value={value[2]} title="Lightness" onInput={onLightness} />

// src/colors/vue/components/inputs/colors/InputHSL.vue
<script setup lang="ts">
import InputNumber from '@vue/components/inputs/base/InputNumber.vue'
import type { HSL } from 'color-convert/conversions'

const props = defineProps<{
  value: HSL
}>()

const emit = defineEmits(['input'])

const onHue = (newHue: number) => {
  const newHSL: HSL = [newHue, props.value[1], props.value[2]]
  emit('input', newHSL)
}

const onSaturation = (newSaturation: number) => {
  const newHSL: HSL = [props.value[0], newSaturation, props.value[2]]
  emit('input', newHSL)
}

const onLightness = (newLightness: number) => {
  const newHSL: HSL = [props.value[0], props.value[1], newLightness]
  emit('input', newHSL)
}
</script>

<template>
  <InputNumber :value="props.value[0]" title="Hue" :max="360" @input="onHue" />
  <InputNumber :value="props.value[1]" title="Saturation" @input="onSaturation" />
  <InputNumber :value="props.value[2]" title="Lightness" @input="onLightness" />
</template>
