// src/colors/svelte/components/inputs/colors/InputHEX.svelte
<script lang="ts">
  import type { HEX } from 'color-convert/conversions'
  import InputString from '@svelte/components/inputs/base/InputString.svelte'

  type Props = {
    value: HEX
    onInput: (value: HEX) => void
  }

  const { value, onInput }: Props = $props()

  let hex = $state(value)

  const onKeyUp = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      onInput(hex)
    }
  }

  const onBlur = () => {
    onInput(hex)
  }
</script>

<InputString {value} title="HEX" maxLength={6} onInput={(hexNew: HEX) => (hex = hexNew)} {onKeyUp} {onBlur} />

// src/colors/react/components/inputs/colors/InputHEX.tsx
import InputString from '@react/components/inputs/base/InputString'
import { useState, type KeyboardEventHandler } from 'react'
import { hex } from '@react/signals'
import { setHEX } from '@react/actions'

const InputHEX = () => {
  const [input, setInput] = useState(hex.value)

  const onInput = (hexNew: string) => {
    setInput(hexNew)
  }

  const onKeyUp: KeyboardEventHandler<HTMLInputElement> = (e) => {
    if (e.key === 'Enter') {
      setHEX(input)
    }
  }

  const onBlur = () => {
    setHEX(input)
  }

  return (
    <InputString value={hex.value} title="HEX" maxLength={6} onInput={onInput} onKeyUp={onKeyUp} onBlur={onBlur} />
  )
}

export default InputHEX
