// src/colors/vue/components/inputs/colors/InputHEX.vue
<script setup lang="ts">
import type { HEX } from 'color-convert/conversions'
import InputString from '@vue/components/inputs/base/InputString.vue'
import { ref } from 'vue'

const props = defineProps<{
  value: HEX
}>()

const hex = ref<string>(props.value)

const emit = defineEmits(['input'])

const onInput = (newHex: string) => {
  hex.value = newHex
}

const onSubmit = () => {
  emit('input', hex.value)
}
</script>

<template>
  <InputString :maxLength="6" :value="props.value" @input="onInput" @keyup.enter="onSubmit" @blur="onSubmit" title="HEX" />
</template>

// src/colors/svelte/components/inputs/colors/InputHEX.svelte
<script lang="ts">
  import type { HEX } from 'color-convert/conversions'
  import InputString from '@svelte/components/inputs/base/InputString.svelte'

  type Props = {
    value: HEX
    onInput: (value: HEX) => void
  }

  const { value, onInput }: Props = $props()

  let hex = $state(value)

  const onKeyUp = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      onInput(hex)
    }
  }

  const onBlur = () => {
    onInput(hex)
  }
</script>

<InputString {value} title="HEX" maxLength={6} onInput={(hexNew: HEX) => (hex = hexNew)} {onKeyUp} {onBlur} />
